/**
 * Search words in Spanish, Chinese and Korean, pointing at the English phrases
 * the parser already understands (lib/search.ts). Vietnamese lives there too.
 */

/** Spanish, written the way normalizeQuery leaves it (lowercase, no accents). */
export const SPANISH: Record<string, string> = {
  comida: "food",
  comer: "eat",
  restaurante: "restaurant",
  restaurantes: "restaurants",
  bebidas: "drinks",
  cafeteria: "coffee",
  cocteles: "cocktails",
  coctel: "cocktail",
  bares: "bars",
  azotea: "rooftop",
  azoteas: "rooftops",
  vino: "wine",
  jugo: "juice",
  atracciones: "attractions",
  museo: "museum",
  museos: "museums",
  "que hacer": "things to do",
  parque: "park",
  parques: "parks",
  muelle: "pier",
  muelles: "piers",
  fotos: "photos",
  vistas: "views",
  compras: "shopping",
  tienda: "shop",
  tiendas: "shop",
  mercado: "market",
  mercados: "markets",
  "segunda mano": "thrift",
  libreria: "bookstore",
  gratis: "free",
  "abierto ahora": "open now",
  hoy: "today",
  "esta noche": "tonight",
  "tarde en la noche": "late night",
  "abre tarde": "open late",
  "abierto tarde": "open late",
  trasnoche: "late night",
  barato: "cheap",
  barata: "cheap",
  economico: "cheap",
  cita: "date night",
  romantico: "romantic",
  lluvia: "rainy",
  lluvioso: "rainy",
  ninos: "kids",
  familia: "family",
  vegetariano: "vegetarian",
  vegetariana: "vegetarian",
  vegano: "vegan",
  vegana: "vegan",
  "sin gluten": "gluten free",
  hamburguesa: "burger",
  hamburguesas: "burgers",
  fideos: "noodles",
  "sopa de fideos": "noodle soup",
  arroz: "rice",
  postre: "dessert",
  postres: "desserts",
  panaderia: "bakery",
  mariscos: "seafood",
  "pollo frito": "fried chicken",
  "comida callejera": "street food",
  vietnamita: "vietnamese",
  coreana: "korean",
  japonesa: "japanese",
  "comida china": "chinese",
  tailandesa: "thai",
  mexicana: "mexican",
  italiana: "italian",
  francesa: "french",
  griega: "greek",
  peruana: "peruvian",
  colombiana: "colombian",
  dominicana: "dominican",
  etiope: "ethiopian",
  filipina: "filipino",
  turca: "turkish",
  polaca: "polish",
  caribena: "caribbean",
  "el bronx": "the bronx",
}

/**
 * Chinese and Korean terms, replaced with English before the query is
 * normalized (normalization keeps only Latin letters). Longest first.
 */
const CJK_PAIRS: [string, string][] = [
  // Chinese (Simplified)
  ["珍珠奶茶", "bubble tea"],
  ["小笼包", "soup dumplings"],
  ["大都会博物馆", "the met"],
  ["帝国大厦", "empire state"],
  ["中央公园", "central park"],
  ["时代广场", "times square"],
  ["唐人街", "chinatown"],
  ["韩国城", "koreatown"],
  ["法拉盛", "flushing"],
  ["威廉斯堡", "williamsburg"],
  ["曼哈顿", "manhattan"],
  ["布鲁克林", "brooklyn"],
  ["皇后区", "queens"],
  ["布朗克斯", "the bronx"],
  ["哈莱姆", "harlem"],
  ["切尔西", "chelsea"],
  ["苏豪", "soho"],
  ["中城", "midtown"],
  ["东村", "east village"],
  ["西村", "west village"],
  ["正在营业", "open now"],
  ["营业时间", "hours"],
  ["几点开门", "hours"],
  ["几点关门", "hours"],
  ["早午餐", "brunch"],
  ["鸡尾酒", "cocktails"],
  ["景点", "attractions"],
  ["博物馆", "museums"],
  ["美术馆", "museums"],
  ["日本料理", "japanese"],
  ["韩国菜", "korean"],
  ["越南菜", "vietnamese"],
  ["泰国菜", "thai"],
  ["中国菜", "chinese"],
  ["意大利", "italian"],
  ["墨西哥", "mexican"],
  ["怎么去", "get to"],
  ["饺子", "dumplings"],
  ["点心", "dumplings"],
  ["披萨", "pizza"],
  ["拉面", "ramen"],
  ["汉堡", "burgers"],
  ["寿司", "sushi"],
  ["咖啡", "coffee"],
  ["奶茶", "bubble tea"],
  ["抹茶", "matcha"],
  ["酒吧", "bars"],
  ["屋顶", "rooftop"],
  ["公园", "parks"],
  ["码头", "piers"],
  ["拍照", "photos"],
  ["购物", "shopping"],
  ["古着", "vintage"],
  ["市集", "market"],
  ["免费", "free"],
  ["今天", "today"],
  ["今晚", "tonight"],
  ["深夜", "late night"],
  ["很晚", "late night"],
  ["便宜", "cheap"],
  ["平价", "cheap"],
  ["约会", "date night"],
  ["浪漫", "romantic"],
  ["雨天", "rainy"],
  ["下雨", "rainy"],
  ["孩子", "kids"],
  ["纯素", "vegan"],
  ["素食", "vegetarian"],
  ["规划", "plan"],
  ["行程", "plan"],
  ["一天", "day"],
  ["机场", "airport"],
  ["地铁", "subway"],
  ["小费", "tip"],
  ["安全", "safety"],
  ["你好", "hello"],
  ["您好", "hello"],
  ["谢谢", "thanks"],
  ["地址", "address"],
  ["甜品", "desserts"],
  ["海鲜", "seafood"],
  ["炸鸡", "fried chicken"],
  ["中餐", "chinese"],
  ["日料", "japanese"],
  ["面条", "noodles"],
  ["米饭", "rice"],
  // Korean
  ["메트로폴리탄 미술관", "the met"],
  ["엠파이어 스테이트", "empire state"],
  ["센트럴 파크", "central park"],
  ["센트럴파크", "central park"],
  ["타임스스퀘어", "times square"],
  ["타임스 스퀘어", "times square"],
  ["이스트 빌리지", "east village"],
  ["이스트빌리지", "east village"],
  ["웨스트 빌리지", "west village"],
  ["웨스트빌리지", "west village"],
  ["차이나타운", "chinatown"],
  ["코리아타운", "koreatown"],
  ["한인타운", "koreatown"],
  ["윌리엄스버그", "williamsburg"],
  ["미드타운", "midtown"],
  ["맨해튼", "manhattan"],
  ["브루클린", "brooklyn"],
  ["브롱크스", "the bronx"],
  ["플러싱", "flushing"],
  ["퀸즈", "queens"],
  ["할렘", "harlem"],
  ["첼시", "chelsea"],
  ["소호", "soho"],
  ["덤보", "dumbo"],
  ["영업시간", "hours"],
  ["영업 중", "open now"],
  ["늦게까지", "late night"],
  ["어떻게 가", "get to"],
  ["프라이드치킨", "fried chicken"],
  ["버블티", "bubble tea"],
  ["밀크티", "bubble tea"],
  ["소룡포", "soup dumplings"],
  ["루프톱", "rooftop"],
  ["명소", "attractions"],
  ["박물관", "museums"],
  ["미술관", "museums"],
  ["빈티지", "vintage"],
  ["데이트", "date night"],
  ["로맨틱", "romantic"],
  ["비 오는", "rainy"],
  ["비오는", "rainy"],
  ["가성비", "cheap"],
  ["브런치", "brunch"],
  ["디저트", "desserts"],
  ["해산물", "seafood"],
  ["베트남", "vietnamese"],
  ["이탈리아", "italian"],
  ["멕시코", "mexican"],
  ["칵테일", "cocktails"],
  ["햄버거", "burgers"],
  ["만두", "dumplings"],
  ["딤섬", "dumplings"],
  ["피자", "pizza"],
  ["라멘", "ramen"],
  ["버거", "burgers"],
  ["스시", "sushi"],
  ["초밥", "sushi"],
  ["커피", "coffee"],
  ["말차", "matcha"],
  ["공원", "parks"],
  ["부두", "piers"],
  ["사진", "photos"],
  ["쇼핑", "shopping"],
  ["시장", "market"],
  ["마켓", "market"],
  ["무료", "free"],
  ["오늘 밤", "tonight"],
  ["오늘밤", "tonight"],
  ["오늘", "today"],
  ["심야", "late night"],
  ["저렴", "cheap"],
  ["채식", "vegetarian"],
  ["비건", "vegan"],
  ["일정", "plan"],
  ["계획", "plan"],
  ["하루", "day"],
  ["공항", "airport"],
  ["지하철", "subway"],
  ["세금", "tax"],
  ["안전", "safety"],
  ["안녕", "hello"],
  ["고마워", "thanks"],
  ["감사", "thanks"],
  ["주소", "address"],
  ["국수", "noodles"],
  ["한식", "korean"],
  ["일식", "japanese"],
  ["중식", "chinese"],
  ["태국", "thai"],
  ["팁", "tip"],
]

const CJK = [...CJK_PAIRS].sort((a, b) => b[0].length - a[0].length)
const HAS_CJK = /[぀-ヿ㐀-鿿가-힯]/

/** Swaps Chinese and Korean search words for English ones; other text is left alone. */
export function expandForeign(q: string): string {
  if (!HAS_CJK.test(q)) return q
  let out = q
  for (const [from, to] of CJK) out = out.split(from).join(` ${to} `)
  return out
}
